name: auth0
description: Auth0 demo with Riverpod

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_appauth: ^4.0.1
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^5.0.2
  hooks_riverpod: ^1.0.4
  http: ^0.13.4
  riverpod: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
